### ISSUE TITLE
Progress indicator doesn't appear as expected if transparent colors are used for track.

### ISSUE THREAD

**Issue by 2307vivek** [2307vivek/Seeker#12]
### Description

The progress indicator doesn't appear as expected if the track/segment color has an alpha property. This is more likely happening because progress indicator overlapes the track/segment using a `BlendMode.SrcIn` which uses the destination opacity in the output layer.

**This happens only when the colors used for Seeker track and progress has some transparency.**
<img width="360" alt="Android Large - 1" src="https://user-images.githubusercontent.com/67380664/218292387-a3445a9f-2b1a-4364-b379-0d90b7853f9d.png">

In the above image the `MaterialTheme.colors.primary.copy(alpha = 0.24f)` is used for the track.

### Expected
<img width="360" alt="Android Large - 2" src="https://user-images.githubusercontent.com/67380664/218292412-54b0a79e-2548-448a-b924-ec534806a88c.png">

**Comment by Maxr1998** [comment]
Is there any progress on this issue? What is the reason for using `SrcIn` originally? What are the reasons against simply changing it to the default blend mode?

**Comment by 2307vivek** [comment]
> What is the reason for using `SrcIn` originally?

Currently `Seeker` is implemented in a way that the underlying track is drawn using several segments, with gaps between them. But the progress indicator and the read ahead indicator is not implemented in segments. So, the readahead indicator or the progress indicator only overlaps with the track only over the segments (not over the gaps). `SrcIn` is used so that the overlying progress indicator masks the underlying track only on the segments and not on the gaps. Conversely, `SrcOver` will also mask over the gaps.

> Is there any progress on this issue?

Currently, I can't find anything about this issue with the blend mode online.

**Comment by Maxr1998** [comment]
I see, thanks for the explanation. I wonder if it would be worth it to draw the progress and read ahead with gaps as well.
Or another blend mode can fix this, but I haven't checked yet.

**Comment by 2307vivek** [comment]
fixed by #42
